// <auto-generated />
using System;
using AplicaçãoSupport.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicaçãoSupport.Migrations
{
    [DbContext(typeof(AplicaçãoSupportDbContext))]
    [Migration("20250331133520_time")]
    partial class time
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AplicaçãoSupport.Models.AgendamentosModels.Agendamentos", b =>
                {
                    b.Property<int>("AgendamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AgendamentoId"));

                    b.Property<int>("AtendenteId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDaRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDoAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotivoAgendamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Realizado")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("AgendamentoId");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Atendente", b =>
                {
                    b.Property<int>("Atendente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Atendente_Id"));

                    b.Property<string>("Nome_Atendente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("Atendente_Id");

                    b.ToTable("Atendente");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Atendimentos", b =>
                {
                    b.Property<int>("Atendimento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Atendimento_Id"));

                    b.Property<int>("AtendenteId")
                        .HasColumnType("int");

                    b.Property<string>("Cliente_Atendido")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data_Atendimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemaApresentado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResolucaoDoProblema")
                        .HasColumnType("longtext");

                    b.HasKey("Atendimento_Id");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ClienteNome")
                        .HasColumnType("longtext");

                    b.Property<string>("ClienteTelefone")
                        .HasColumnType("longtext");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Nome_Empresa")
                        .HasColumnType("longtext");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.AgendamentosModels.Agendamentos", b =>
                {
                    b.HasOne("AplicaçãoSupport.Models.Atendente", "Atendente")
                        .WithMany()
                        .HasForeignKey("AtendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicaçãoSupport.Models.Clientes", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Atendimentos", b =>
                {
                    b.HasOne("AplicaçãoSupport.Models.Atendente", "Atendente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("AtendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicaçãoSupport.Models.Empresa", "Empresa")
                        .WithMany("Atendimentos")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Atendente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Clientes", b =>
                {
                    b.HasOne("AplicaçãoSupport.Models.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Atendente", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Clientes", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.Empresa", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
